#!/usr/bin/env python

import argparse
import json as JSON
import requests
import yaml

import re

class ParsePage(object):
    def __init__(self, page):
        self.page = page
        self._comment = None

    @property
    def comment(self):
        if not self._comment:

            html = requests.get(f"https://review.opendev.org/changes/{self.page}?o=MESSAGES", headers={"Content-Type": "application/json;charset=UTF-8"})
            json = JSON.loads(html.text[5:])
            messages = json['messages']
            for idx in range(len(messages)-1, -1, -1):
                if 'tag' in messages[idx]:
                    if messages[idx]['tag'] == "autogenerated:zuul:check":
                        self._comment = messages[idx]['message']
                        break
        return self._comment

    def find_job_url(self, regexp):
        regex = re.compile("{} (http.?://[^ ]+)".format(regexp))
        match = re.findall(regex, self.comment)

        if match:
            return match[0]
        return None


class Review(object):
    def __init__(self, review, template, job):
        self.review = review
        self.template = template
        self.job = job
        self.url = ''

    @staticmethod
    def find_log_url(base_url):
        """Get the next raw <a> element relative to a element from regexp"""

        url = requests.get(base_url.replace('/t/','/api/tenant/')).json()['log_url']
        print(url)
        return url

    def final_yaml_def(self, url):
        reproducer = requests.get(url).text

        job_yaml = yaml.safe_load(reproducer)
        template_def = ""
        with open(self.template, "r") as f:
            template_def = yaml.safe_load(f)
        vars_def = template_def[0]['tasks'][0]['vars']

        vars_def['depends_on'] = job_yaml[2]['vars']['depends_on']
        vars_def['zuul_yaml'] = job_yaml[2]['vars']['zuul_yaml']
        if 'launch_job_branch' in job_yaml[2]['vars']:
            vars_def['launch_job_branch'] = job_yaml[2]['vars']['launch_job_branch']
        return yaml.safe_dump(template_def)

class UpdateJob(object):
    """Create the hash variable suitable for an update jobs.

    By-pass the need for an already run reproducer or when the review
    doesn't have the multinode-overcloud-update.yml defined.

    OVERCLOUD_DEPLOY_RELEASE : stable_release -> master/train ...
    OVERCLOUD_DEPLOY_HASH: current_hash ->
        https://trunk.rdoproject.org/centos8-master/previous-current-tripleo/delorean.repo.md5
    OVERCLOUD_TARGET_RELEASE: stable_release -> master/train ...
    OVERCLOUD_TARGET_HASH:  current-tripleo ->
        https://trunk.rdoproject.org/centos8-master/current-tripleo/delorean.repo.md5
    UNDERCLOUD_INSTALL_RELEASE: stable_release -> master/train ...
    # Assume already updated undercloud ?
    UNDERCLOUD_INSTALL_HASH: current_hash ->
        https://trunk.rdoproject.org/centos8-master/previous-current-tripleo/delorean.repo.md5
    UNDERCLOUD_TARGET_RELEASE: stable_release: master/train
    # is undercloud update happening when doing multinode-overcloud-update.yml ?
    UNDERCLOUD_TARGET_HASH:

    The featureset037 is the one holding the update definition.  It
    does only the overcloud update.

    It's defined like this TOCI_JOBTYPE=multinode-1ctlr-featureset037 which is set there:
    https://github.com/openstack/tripleo-ci/blob/master/zuul.d/multinode-jobs.yaml#L538..L553
    in tripleo-ci-centos-8-scenario000-multinode-oooq-container-updates. This defines the critical:

      nodes: 1ctlr
      featureset: '037'

    TODO: Whould be nice to have nodes: 3ctlr_1comp and featureset037 with undercloud update.

    It's then run the trivial
    https://github.com/openstack/tripleo-quickstart-extras/blob/master/playbooks/multinode-overcloud-update.yml#L1..L10
    to get the overcloud update done.

    This is the command for the deployment ... OUCH!!:

    /home/zuul/workspace/.quickstart/bin/ansible-playbook \
      --tags build,undercloud-setup,\
             undercloud-scripts,undercloud-install,undercloud-post-install,\
             tripleo-validations,overcloud-scripts,\
             overcloud-prep-config,overcloud-prep-containers,\
             overcloud-deploy,overcloud-post-deploy,\
             overcloud-validate,overcloud-update \
      --extra-vars @/home/zuul/workspace/.quickstart/config/release/tripleo-ci/CentOS-8/master.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/nodes/1ctlr.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset-multinode-common.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset037.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-ci/toci-quickstart/config/testenv/multinode.yml \
      --extra-vars @/home/zuul/workspace/logs/role-vars.yaml \
      -e toci_vxlan_networking=false \
      -e vxlan_networking=false \
      --extra-vars local_working_dir=/home/zuul/workspace/.quickstart \
      --extra-vars virthost=127.0.0.2 \
      --inventory /home/zuul/workspace/.quickstart/hosts \
      --extra-vars tripleo_root=/home/zuul/src/opendev.org/openstack \
      --extra-vars working_dir=/home/zuul \
      --extra-vars tripleo_generate_scripts=true \
      --skip-tags tripleo-validations,teardown-all \
      --extra-vars @/home/zuul/workspace/logs/zuul-variables.yaml \
      --extra-vars @/home/zuul/workspace/logs/hostvars-variables.yaml \
      /home/zuul/workspace/.quickstart/playbooks/quickstart.yml

    /home/zuul/workspace/.quickstart/bin/ansible-playbook --tags build,undercloud-setup,undercloud-scripts,undercloud-install,undercloud-post-install,tripleo-validations,overcloud-scripts,overcloud-prep-config,overcloud-prep-containers,overcloud-deploy,overcloud-post-deploy,overcloud-validate,overcloud-update --extra-vars @/home/zuul/workspace/.quickstart/config/release/tripleo-ci/CentOS-8/master.yml \
      -e dlrn_hash=dbedb13317b98fbb75e58951331e5b65 \
      -e get_build_command=dbedb13317b98fbb75e58951331e5b65 \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/nodes/1ctlr.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset-multinode-common.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset037.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-ci/toci-quickstart/config/testenv/multinode.yml --extra-vars @/home/zuul/workspace/logs/role-vars.yaml -e toci_vxlan_networking=false -e vxlan_networking=false --extra-vars local_working_dir=/home/zuul/workspace/.quickstart --extra-vars virthost=127.0.0.2 --inventory /home/zuul/workspace/.quickstart/hosts --extra-vars tripleo_root=/home/zuul/src/opendev.org/openstack --extra-vars working_dir=/home/zuul --extra-vars tripleo_generate_scripts=true --skip-tags tripleo-validations,teardown-all --extra-vars @/home/zuul/workspace/logs/zuul-variables.yaml --extra-vars @/home/zuul/workspace/logs/hostvars-variables.yaml \
      /home/zuul/workspace/.quickstart/playbooks/multinode-undercloud.yml

    /home/zuul/workspace/.quickstart/bin/ansible-playbook --tags build,undercloud-setup,undercloud-scripts,undercloud-install,undercloud-post-install,tripleo-validations,overcloud-scripts,overcloud-prep-config,overcloud-prep-containers,overcloud-deploy,overcloud-post-deploy,overcloud-validate,overcloud-update --extra-vars @/home/zuul/workspace/.quickstart/config/release/tripleo-ci/CentOS-8/master.yml \
      -e dlrn_hash=63ce0a5a8ad9f21de01c8306e6472bc5 \
      -e get_build_command=63ce0a5a8ad9f21de01c8306e6472bc5 \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/nodes/1ctlr.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset-multinode-common.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset037.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-ci/toci-quickstart/config/testenv/multinode.yml --extra-vars @/home/zuul/workspace/logs/role-vars.yaml -e toci_vxlan_networking=false -e vxlan_networking=false --extra-vars local_working_dir=/home/zuul/workspace/.quickstart --extra-vars virthost=127.0.0.2 --inventory /home/zuul/workspace/.quickstart/hosts --extra-vars tripleo_root=/home/zuul/src/opendev.org/openstack --extra-vars working_dir=/home/zuul --extra-vars tripleo_generate_scripts=true --skip-tags tripleo-validations,teardown-all --extra-vars @/home/zuul/workspace/logs/zuul-variables.yaml --extra-vars @/home/zuul/workspace/logs/hostvars-variables.yaml \
      /home/zuul/workspace/.quickstart/playbooks/multinode-overcloud-prep.yml

    /home/zuul/workspace/.quickstart/bin/ansible-playbook --tags build,undercloud-setup,undercloud-scripts,undercloud-install,undercloud-post-install,tripleo-validations,overcloud-scripts,overcloud-prep-config,overcloud-prep-containers,overcloud-deploy,overcloud-post-deploy,overcloud-validate,overcloud-update --extra-vars @/home/zuul/workspace/.quickstart/config/release/tripleo-ci/CentOS-8/master.yml \
      -e dlrn_hash=63ce0a5a8ad9f21de01c8306e6472bc5 \
      -e get_build_command=63ce0a5a8ad9f21de01c8306e6472bc5 \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/nodes/1ctlr.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset-multinode-common.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset037.yml --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-ci/toci-quickstart/config/testenv/multinode.yml --extra-vars @/home/zuul/workspace/logs/role-vars.yaml -e toci_vxlan_networking=false -e vxlan_networking=false --extra-vars local_working_dir=/home/zuul/workspace/.quickstart --extra-vars virthost=127.0.0.2 --inventory /home/zuul/workspace/.quickstart/hosts --extra-vars tripleo_root=/home/zuul/src/opendev.org/openstack --extra-vars working_dir=/home/zuul --extra-vars tripleo_generate_scripts=true --skip-tags tripleo-validations,teardown-all --extra-vars @/home/zuul/workspace/logs/zuul-variables.yaml --extra-vars @/home/zuul/workspace/logs/hostvars-variables.yaml \
      /home/zuul/workspace/.quickstart/playbooks/multinode-overcloud.yml --extra-vars 'validation_args='\''--validation-errors-nonfatal'\'''

    This is the final command run for the update... OUCH!!:

    /home/zuul/workspace/.quickstart/bin/ansible-playbook \
      --tags build,undercloud-setup,\
             undercloud-scripts,undercloud-install,undercloud-post-install,\
             tripleo-validations,overcloud-scripts,\
             overcloud-prep-config,overcloud-prep-containers,\
             overcloud-deploy,overcloud-post-deploy,\
             overcloud-validate,overcloud-update \
      --extra-vars @/home/zuul/workspace/.quickstart/config/release/tripleo-ci/CentOS-8/master.yml \
      -e dlrn_hash=63ce0a5a8ad9f21de01c8306e6472bc5 \
      -e get_build_command=63ce0a5a8ad9f21de01c8306e6472bc5 \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/nodes/1ctlr.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset-multinode-common.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-quickstart/config/general_config/featureset037.yml \
      --extra-vars @/home/zuul/src/opendev.org/openstack/tripleo-ci/toci-quickstart/config/testenv/multinode.yml \
      --extra-vars @/home/zuul/workspace/logs/role-vars.yaml \
      -e toci_vxlan_networking=false \
      -e vxlan_networking=false \
      --extra-vars local_working_dir=/home/zuul/workspace/.quickstart \
      --extra-vars virthost=127.0.0.2 \
      --inventory /home/zuul/workspace/.quickstart/hosts \
      --extra-vars tripleo_root=/home/zuul/src/opendev.org/openstack \
      --extra-vars working_dir=/home/zuul \
      --extra-vars tripleo_generate_scripts=true \
      --skip-tags tripleo-validations,teardown-all \
      --extra-vars @/home/zuul/workspace/logs/zuul-variables.yaml \
      --extra-vars @/home/zuul/workspace/logs/hostvars-variables.yaml \
      /home/zuul/workspace/.quickstart/playbooks/multinode-overcloud-update.yml

    """


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("-r", "--review", type=str)
    parser.add_argument("-t", "--template", type=str)
    parser.add_argument("-j", "--job", type=str)
    options = parser.parse_args()

    review = Review(options.review, options.template, options.job)
    zuul_url = ParsePage(options.review).find_job_url(options.job)
    log_url = review.find_log_url(zuul_url)
    yaml = review.final_yaml_def(f"{log_url}logs/reproducer-quickstart/launcher-playbook.yaml")

    print(f"reproducer YAML for review https://review.opendev.org/{options.review}")
    print("=========================")
    print(yaml)


if __name__ == '__main__':
    main()
