# Destroy everything.
- name: Destroy everything related to the reproducer runner instance
  hosts: localhost
  gather_facts: false
  vars:
    env_name: "{{ prefix }}"
  tasks:
    - name: Which server would I delete
      debug:
        msg:  "Would destroy {{ env_name }} instance"

    - name: destroy the instance
      os_server:
        state: absent
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}"
      when: not noop|default(false)|bool

    - name: list associated servers
      os_server_info:
        cloud: openstack
        server: "*{{ env_name }}-openstack*"
      register: servers

    - name: destroy them
      os_server:
        state: absent
        cloud: "{{ cloud_name }}"
        name: "{{ item.name }}"
      loop: "{{ servers.openstack_servers|default([]) }}"
      loop_control:
        label: "{{ item.name }}"
      when: not noop|default(false)|bool

    - name: Which associated server would I delete
      debug:
        msg:  "Would destroy '{{ item.name }}' instance"
      loop: "{{ servers.openstack_servers|default([]) }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Which key be deleted
      debug:
        msg:  "Would destroy {{ env_name }} key"

    - name: delete the key
      os_keypair:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}"
        state: absent
      when:
        - delete_key|default("False")|bool
        - not noop|default(false)|bool

    - name: Which appcred be deleted
      debug:
        msg:  "Would destroy {{ env_name }} appcred"

    - name: destroy application credential
      os_application_credentials:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}"
        state: absent
      when:
        - delete_appcred|default("False")|bool
        - not noop|default(false)|bool

    - name: Which router be deleted
      debug:
        msg:  "Would destroy {{ env_name }}-router router"

    - name: destroy a router
      os_router:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}-router"
        state: absent
      when: not noop|default(false)|bool

    - name: destroy the reproducer subnet
      os_subnet:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}-subnet"
        network_name: "{{ env_name }}-net"
        state: absent
        enable_dhcp: yes
        cidr: 192.168.0.0/24
        dns_nameservers:
           - 10.11.5.19
           - 10.10.160.2
           - 10.5.30.160
           - 8.8.8.7
           - 8.8.8.8
        wait: yes
      when: not noop|default(false)|bool

    - name: destroy the reproducer network
      os_network:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}-net"
        state: absent
        external: false
        shared: no
        wait: yes
      when: not noop|default(false)|bool

    - name: destroy security group rule for ping
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group rule for SSH
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group rule for Gerrit
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group rule for Zuul
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: tcp
        port_range_min: 9000
        port_range_max: 9000
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group rule for Logs
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: tcp
        port_range_min: 8000
        port_range_max: 8000
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group rule for git/review access.
      os_security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ env_name }}-security-group"
        state: absent
        protocol: tcp
        port_range_min: 29418
        port_range_max: 29418
        remote_ip_prefix: 0.0.0.0/0
      when: not noop|default(false)|bool

    - name: destroy security group
      os_security_group:
        cloud: "{{ cloud_name }}"
        name: "{{ env_name }}-security-group"
        state: absent
        description: Security group for reproducer instances
      when: not noop|default(false)|bool
